config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: { sessions: 'clients/sessions' }

  concern :groups_and_role_management do
    get 'groups' => 'groups#index'
    post 'groups' => 'accounts#add_to_group', as: :add_to_group
    delete 'groups/:group_uuid' => 'accounts#remove_from_group', as: :remove_from_group
    get 'roles' => 'roles#index'
    post 'roles' => 'accounts#add_role', as: :add_role
    delete 'roles/:role_uuid' => 'accounts#revoke_role', as: :revoke_roles
  end

  scope :admin do
    resources :groups, param: :uuid, module: 'api/v2' do
      get 'accounts' => 'accounts#index'
    end
    resources :roles, param: :uuid, module: 'api/v2'
    resources :accounts, param: :uuid, module: 'api/v2', concerns: :groups_and_role_management
  end

  namespace :api, defaults: {format: :json} do
    namespace :v2 do
      resources :groups, param: :uuid do
        get 'accounts' => 'accounts#index'
      end
      resources :roles, param: :uuid
      resources :accounts, param: :uuid, concerns: :groups_and_role_management
      post 'accounts/reserve_next_id_soce' => 'accounts#reserve_next_id_soce'
    end
  end

  resources :clients do
    post 'add_role'
    post 'remove_role'
  end

  root "clients#index"
end

app/views/shared/_flashes.html.haml
- if notice.present?
  %p#notice= flash[:notice]

- if alert.present?
  %p#alert= flash[:alert]

app/views/shared/_menu.html.haml
-#=cache(action_suffix: "primary") do
%aside.sidebar
  .plm.prm.int
    #navigation
      #logo
        =link_to root_path do
          =image_tag "logo_alumni.png"
      #menu-button
        .menu-item>
          =link_to "#" do
            %i.zmdi.zmdi-menu
      %nav
        -if client_signed_in?
          .menu-item>
            =link_to "Clients de l'API", clients_path, class: "menu-a"
          .menu-item>
            =link_to "Comptes", accounts_path, class: "menu-a"
          .menu-item>
            =link_to "Groupes", groups_path, class: "menu-a"
          .menu-item>
            =link_to "Roles", roles_path, class: "menu-a"
          .menu-item>
            =link_to "Déconnexion", destroy_client_session_path	, class: "menu-a", method: :delete
        -else
          .menu-item>
            =link_to "Connexion", new_client_session_path	, class: "menu-a"