config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: { sessions: 'clients/sessions' }

  concern :groups_and_role_management do
    get 'groups' => 'groups#index'
    post 'groups' => 'accounts#add_to_group', as: :add_to_group
    delete 'groups/:group_uuid' => 'accounts#remove_from_group', as: :remove_from_group
    get 'roles' => 'roles#index'
    post 'roles' => 'accounts#add_role', as: :add_role
    delete 'roles/:role_uuid' => 'accounts#revoke_role', as: :revoke_roles
  end

  scope :admin do
    resources :groups, param: :uuid, module: 'api/v2' do
      get 'accounts' => 'accounts#index'
    end
    resources :roles, param: :uuid, module: 'api/v2'
    resources :accounts, param: :uuid, module: 'api/v2', concerns: :groups_and_role_management
  end

  namespace :api, defaults: {format: :json} do
    namespace :v2 do
      resources :groups, param: :uuid do
        get 'accounts' => 'accounts#index'
      end
      resources :roles, param: :uuid
      resources :accounts, param: :uuid, concerns: :groups_and_role_management
      post 'accounts/reserve_next_id_soce' => 'accounts#reserve_next_id_soce'
    end
  end

  resources :clients do
    post 'add_role'
    post 'remove_role'
  end

  root "clients#index"
end

app/models/client.rb
class Client < ApplicationRecord
  rolify
  acts_as_token_authenticatable

  validates :email, presence: false

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable

  #this method is called by devise to check for "active" state of the model
  def active_for_authentication?
    super && active?
  end

  def active?
    self.active
  end

  # Override some Rolify class ton restrict roles types
  def add_role(role_name, resource = nil)
    if resource == nil
      super if Role.list_availables.include? [role_name]
    else
      super if Role.list_availables.include? [role_name, resource]
    end
  end
end

app/controllers/clients/sessions_controller.rb
class Clients::SessionsController < Devise::SessionsController
  skip_before_action :verify_authenticity_token

  respond_to :json

  def after_sign_out_path_for(resource)
    new_client_session_path
  end

  # TODO: get rid of this custom behavior :
  # API clients should use token instead
  def create
    # default behavior for html requests
    return super if request.format.html?

    # handle json authentications
    resource = Client.find_by(name: client_params[:name])

    return invalid_login_attempt unless resource

    if resource.valid_password?(client_params[:password])
      sign_in("client", resource)

      @client = resource
      render "clients/show", status: :created
    else
      invalid_login_attempt
    end
  end

  protected

  def client_params
    params.require(:client).permit(:name, :password)
  end

  def invalid_login_attempt
    warden.custom_failure!
    render json: {
             success: false, message: "Error with your login or password"
           },
           status: 401
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
    authorize @clients, :index?
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    authorize @client, :index?
    @roles = Role.list_availables
  end

  # GET /clients/new
  def new
    @client = Client.new
    authorize @client, :create?
  end

  # GET /clients/1/edit
  def edit
    authorize @client, :edit?
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    authorize @client, :create?
    respond_to do |format|
      if @client.save
        format.html do
          redirect_to @client, notice: "Client was successfully created."
        end
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json do
          render json: @client.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    authorize @client, :edit?
    respond_to do |format|
      if @client.update(client_params)
        format.html do
          redirect_to @client, notice: "Client was successfully updated."
        end
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json do
          render json: @client.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    authorize @client, :destroy?
    @client.destroy
    respond_to do |format|
      format.html do
        redirect_to clients_url, notice: "Client was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  def add_role
    client = Client.find(params[:client_id])
    authorize client, :edit?
    role_name = params[:role_name]
    ressource = params[:ressource]
    ressource = ressource.constantize unless ressource.nil?
    client.add_role(role_name.to_sym, ressource)
    redirect_to client_url(client), notice: "Role ajouté"
  end

  def remove_role
    client = Client.find(params[:client_id])
    authorize client, :edit?
    role_name = params[:role_name]
    ressource = params[:ressource]
    ressource = ressource.constantize unless ressource.nil?
    client.remove_role(role_name.to_sym, ressource)
    redirect_to client_url(client), notice: "Role retiré"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(
      :name,
      :password,
      :description,
      :active,
      :email,
      :authentication_token,
    )
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for(@client) do |f|
  - if @client.errors.any?
    #error_explanation
      %h2
        = pluralize(@client.errors.count, "error")
        prohibited this client from being saved:
      %ul
        - @client.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :password
    %br/
    = f.text_field :password
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :active
    %br/
    = f.check_box :active
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :authentication_token
    %br/
    = f.text_field :authentication_token
  .actions
    = f.submit

app/views/clients/edit.html.haml
%h1 Editing Client
= render 'form'
= link_to 'Show', @client

= link_to 'Back', clients_path

app/views/clients/index.html.haml
%h1 Listing Clients
%table.table-auto.table-striped
  %thead
    %tr
      %th Name
      %th Password
      %th Description
      %th Active
      %th Email
      %th Authentication token
      %th{:colspan => "3"}
  %tbody
    - @clients.each do |client|
      %tr
        %td= client.name
        %td= client.password
        %td= client.description
        %td= client.active
        %td= client.email
        %td= client.authentication_token
        %td= link_to 'Show', client
        %td= link_to 'Edit', edit_client_path(client)
        %td= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Client', new_client_path

app/views/clients/new.html.haml
%h1 New Client
= render 'form'
= link_to 'Back', clients_path

app/views/clients/show.html.haml
%p
  %strong Name:
  = @client.name
%p
  %strong Password:
  = @client.password
%p
  %strong Description:
  = @client.description
%p
  %strong Active:
  = @client.active
%p
  %strong Email:
  = @client.email
%p
  %strong Authentication token:
  = @client.authentication_token
%p
  %strong Rôles:
  Attention, les rôles sans scopes sont préponderant sur les rôles avec scopes.
  %table
    %thead
      %tr
        %th Role
        %th Scope
        %th Attribué ?
        %th
    %tbody
      - @roles.each do |role|
        %tr
          %td #{role[0]}
          %td= role[1] ? role[1].to_s.singularize.capitalize : "all"
          %td= role[1].nil? ? @client.has_role?(role[0]) : @client.has_role?(role[0], role[1])
          %td= link_to 'Ajouter', client_add_role_path(@client, role_name: role[0], ressource: role[1]), method: :post
          %td= link_to 'Retirer', client_remove_role_path(@client, role_name: role[0], ressource: role[1]), method: :post

= link_to 'Edit', edit_client_path(@client)
|
= link_to 'Back', clients_path